#!/bin/sh
set -e

if [ -e /etc/default/locale ]; then
    . /etc/default/locale
fi
if [ -e $HOME/.locale ]; then
    . $HOME/.locale
fi

for i in $LC_COLLATE $LC_CTYPE $LC_MONETARY $LC_MESSAGES \
         $LC_NUMERIC $LC_TIME $LC_ALL $LANGUAGE; do
    if ! [ -d /usr/lib/locale/$i ]; then
        genlocale ${i%.UTF-8}
    fi
done
